from src.pages.base_page import BasePage
from selenium.webdriver.common.by import By

class AddProfilePage(BasePage):
    guidelines_header = (By.CSS_SELECTOR, '.well p')
    guidelines_list = (By.CSS_SELECTOR, '.well ul li')

    alert_message = (By.CSS_SELECTOR, '.alert-notice')
    alert_dialog_close = (By.CSS_SELECTOR, '.alert-notice .close')

    document_input = (By.CSS_SELECTOR, '#person_document')
    avatar_input = (By.CSS_SELECTOR, '#person_avatar')
    salutation_input = (By.CSS_SELECTOR, '#person_salutation')
    firstname_input = (By.CSS_SELECTOR, '#person_first_name')
    lastname_input = (By.CSS_SELECTOR, '#person_last_name')
    emailaddress_input = (By.CSS_SELECTOR, '#person_email_address')
    phonenumber_input = (By.CSS_SELECTOR, '#person_phone_number')
    linkedin_profile_url_input = (By.CSS_SELECTOR, '#person_linkedin_profile_url')
    location_input = (By.CSS_SELECTOR, '#person_location')
    description_input = (By.CSS_SELECTOR, '#person_description')
    salary_input = (By.CSS_SELECTOR, '#person_salary')
    salary_details_input = (By.CSS_SELECTOR, '#person_salary_details')
    remote_interest_input = (By.CSS_SELECTOR, '#person_remote_interest')
    position_interest_input = (By.CSS_SELECTOR, '#person_position_interest')
    experience_years_input = (By.CSS_SELECTOR, '#person_experience_years')
    job_search_stage_input = (By.CSS_SELECTOR, '#person_job_search_stage')
    industry_input = (By.CSS_SELECTOR, '#person_industry')
    specialties_input = (By.CSS_SELECTOR, '#person_specialties')
    summary_input = (By.CSS_SELECTOR, '#person_summary')

    document_label = (By.CSS_SELECTOR, 'label[for="person_document"]')
    avatar_label = (By.CSS_SELECTOR, 'label[for="person_avatar"]')
    salutation_label = (By.CSS_SELECTOR, 'label[for="person_salutation"]')
    firstname_label = (By.CSS_SELECTOR, 'label[for="person_first_name"]')
    lastname_label = (By.CSS_SELECTOR, 'label[for="person_last_name"]')
    emailaddress_label = (By.CSS_SELECTOR, 'label[for="person_email_address"]')
    phonenumber_label = (By.CSS_SELECTOR, 'label[for="person_phone_number"]')
    linkedin_profile_url_label = (By.CSS_SELECTOR, 'label[for="person_linkedin_profile_url"]')
    location_label = (By.CSS_SELECTOR, 'label[for="person_location"]')
    description_label = (By.CSS_SELECTOR, 'label[for="person_description"]')
    salary_label = (By.CSS_SELECTOR, 'label[for="person_salary"]')
    salary_details_label = (By.CSS_SELECTOR, 'label[for="person_salary_details"]')
    remote_interest_label = (By.CSS_SELECTOR, 'label[for="person_remote_interest"]')
    position_interest_label = (By.CSS_SELECTOR, 'label[for="person_position_interest"]')
    experience_years_label = (By.CSS_SELECTOR, 'label[for="person_experience_years"]')
    job_search_stage_label = (By.CSS_SELECTOR, 'label[for="person_job_search_stage"]')
    industry_label = (By.CSS_SELECTOR, 'label[for="person_industry"]')
    specialties_label = (By.CSS_SELECTOR, 'label[for="person_specialties"]')
    summary_label = (By.CSS_SELECTOR, 'label[for="person_summary"]')

    save_button = (By.CSS_SELECTOR, '.btn-success')
