from src.pages.base_page import BasePage
from selenium.webdriver.common.by import By

class SearchPage(BasePage):

    top_search_input = (By.CSS_SELECTOR, '#search_keyword')
    search_top_button = (By.CSS_SELECTOR, '.submit_new_search')
    search_button = (By.CSS_SELECTOR, 'input[type="submit"][value="Find Candidate"][class*="btn-secondary"]')
    cancel_button = (By.CSS_SELECTOR, '#new_search input[type="cancel"]')
    label_titles = (By.CSS_SELECTOR, 'label[for*="search_titles"]')
    titles_button = (By.CSS_SELECTOR, '.titles_button')
    titles_input = (By.CSS_SELECTOR, '#search_titles')
    label_locations = (By.CSS_SELECTOR, 'label[for*="search_locations"]')
    locations_button = (By.CSS_SELECTOR, '.locations_button')
    locations_input = (By.CSS_SELECTOR, '#search_locations')
    label_skills = (By.CSS_SELECTOR, 'label[for*="search_skills"]')
    skills_button = (By.CSS_SELECTOR, '.skills_button')
    skills_input = (By.CSS_SELECTOR, '#search_skills')
    label_employers = (By.CSS_SELECTOR, 'label[for*="search_employers"]')
    employers_button = (By.CSS_SELECTOR, '.employers_button')
    employers_input =(By.CSS_SELECTOR,  '#search_employers')
    label_disciplines = (By.CSS_SELECTOR, 'label[for*="search_disciplines"]')
    disciplines_button = (By.CSS_SELECTOR, '.disciplines_button')
    disciplines_input = (By.CSS_SELECTOR, '#search_disciplines')
    label_schools = (By.CSS_SELECTOR, 'label[for*="search_schools"]')
    schools_button = (By.CSS_SELECTOR, '.schools_button')
    school_input = (By.CSS_SELECTOR, '#search_schools')
    min_education_level = (By.CSS_SELECTOR, '#search_min_education_level')
    top_school_checkbox = (By.CSS_SELECTOR, '#search_top_school')
    top_school_tooltip = (By.CSS_SELECTOR, '.search_top_school .tooltip-search div')
    top_company_checkbox = (By.CSS_SELECTOR, '#search_top_company')
    top_company_tooltip = (By.CSS_SELECTOR, '.search_top_company .tooltip-search div')
    active_profile_checkbox = (By.CSS_SELECTOR, '#search_active')
    avail_phone_number_checkbox = (By.CSS_SELECTOR, '#search_phone_number_available')
    avail_email_checkbox = (By.CSS_SELECTOR, '#search_email_available')
    label_keyword = (By.CSS_SELECTOR, 'label[for*="search_keyword2"]')
    keyword_button = (By.CSS_SELECTOR, '.keyword_button')
    keyword_input = (By.CSS_SELECTOR, '#search_keyword2')

    # Old UI elements
    degrees_input = (By.CSS_SELECTOR, '#new_search #search_degrees')
    names_input = (By.CSS_SELECTOR, '#new_search #search_names')
    experiences_input = (By.CSS_SELECTOR, '#new_search #search_experience_years')
    fulltime_checkbox = (By.CSS_SELECTOR, '#new_search #search_job_type_full_time')
    contract_checkbox = (By.CSS_SELECTOR, '#new_search #search_job_type_contract')
    relocate_checkbox = (By.CSS_SELECTOR, '#new_search #search_relocation')
    remote_checkbox = (By.CSS_SELECTOR, '#new_search #search_remote')
    recently_joined_checkbox = (By.CSS_SELECTOR, '#new_search #search_recently_added')

    # search results elements
    total_candidates_text = (By.CSS_SELECTOR, '.total-candidates')
    candidate_grid = (By.CSS_SELECTOR, '.grid-candidate')
    candidate_title = (By.CSS_SELECTOR, '.grid-candidate .employer_candidate_title > a')
    candidate_job_title = (By.CSS_SELECTOR, '.grid-candidate .grid-name-intro p')
    candidate_skills = (By.CSS_SELECTOR, '.grid-skillz-text')
